version: "3.7"
services:
  api:
    volumes:
      - ./:/app
    env_file:
      - .env
    build: backend
    image: headsrooms/girlsintech:latest
    networks:
      - nginx_network
    command: /usr/local/poetry/bin/poetry run uvicorn api.app:app --port 8000 --host 0.0.0.0 --env-file .env
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - nginx_network
networks:
  nginx_network:
    driver: bridge