version: "3.7"
services:
  api:
    volumes:
      - ./:/app
    env_file:
      - .env
    build: .
    command: /usr/local/poetry/bin/poetry run uvicorn api.app:app --port 8000 --host 0.0.0.0 --env-file .env